---
title: "Introduction"
output:
  html_document:
    toc: true
    number_sections: true
author: "by: Stijn van Helmondt"
bibliography: references.bib


---

# Introduction

In his famous research @milgram1967small found that on average there are most three connections separating two random Americans. More recently, @bakhshandeh2011degrees found that between two random Twitter users there is an average degree of separation of 3.43 connections. This means that between two randomly selected Twitter users, there are on average three or four Twitter users in between these randomly selected users. 

Such network analyses can not only be performed on Twitter data, but also in the context of science. Since 1996 the percentage of single-author papers has rapidly decreased. Where in 1996, 50 percent of all published papers in economics journals were single-author papers, in 2021 just 2,1 percent of all papers were written by just one author [@Choueiry_2022; @LSoE_2018]. On the other hand, there has been a major rise in papers with three authors [@LSoE_2018]. 

With the rise of the amount of multi-author papers is also the rise of the internet. The ability of being able to connect to others around the world, and have access to others' papers more easily, makes for one reason for the increase of multi-author papers [@hoekman2010research; @olson2000distance]. In the literature, papers with more than one author are also referred to as co-authorship, or when used to refer to a network 'co-authorship networks' [@fonseca2016co].

This increase of multi-author papers, and the online availability of information surrounding the authors, creates opportunities to look at collaborations from a different perspective. Previous research (e.g. @gallivan2015co) show that working on papers with multiple people can lead to the utilization of different individual strengths to write a better paper. In this paper I will be trying to understand the relation between the preferences of researchers by taking a social network perspective. This perspective follows a different logic than 'mainstream' science, as in this perspective it is acknowledged that people do not 'stand alone', but are embedded in a network of people that (unconsciouly) influence the behaviour of the ego [@SNASS2022]. However, there are several factors that influence the behaviour of the ego, for example gender, similarity in popularity or position within science [@kumar2015co].

Currently, there are fewer women in academia, and especially in higher positions within science [@womeninacademia]. This is contrasting to the percentage of students that enter university, where there is a small majority of women entering into the first year of studies [@womeninacademia]. With this paper, I try to contribute to the knowledge about and understanding of the gender inequality in the scientific world. Furthermore, with this paper I hope to add to the understanding of how social networks, specifically co-authorship network, evolve over time, and how preferences over time. With this I want to contribute to the literature on how preferences can change over time. One interesting addition compared to previous research is that I use webscraped data that include papers that have been published after the COVID-19 pandemic, by using this recent data, I will hopefully be able to contribute to the understand changes that have happened during and after the COVID-19 pandemic and the societal changes that have taken place in this period. This leads me to the first, descriptive, research question: 'How often do researchers work with a person that has the same gender as them? Is this ratio the same for men as for women?'

Furthermore, I would like to investigate potential mechanisms that explain network effects. To study the potential network effects I aim to answer the following research question: 'What mechanisms can help explain the difference in preference of gender when looking for people to work on an academic paper?' More specifically, I will be trying to add to the understanding whether productivity (the number of total published papers), career age and number of co-authors This second research question will be answered by using Stochastic Actor-Orientated Modelling (SOAM) of RSiena [@ripley2011manual]. This enables the investigation the effects of productivity, career age, number of co-authors on collaboration. All of this whilst controlling for structural network effects and other network characteristics .


# References
