---
title: "Theory"
output:
  html_document:
    toc: true
    number_sections: true
author: "by: Stijn van Helmondt"
bibliography: references.bib
csl: apa.csl

---

# Theory

Furthermore, in previous research it has been found that people prefer to (keep) contact with people that are similar to them (e.g. @mcpherson2001birds). Similarity can be seen as something that can arise based on a multitude of identities, such as gender, age, educational level etc. [@mcpherson2001birds]. This effect is called homophily [@mcpherson2001birds]. Homophily is used to understand a multitude of types of social ties, such as friendships, partner preference, but also network structure in academic publications [@mcpherson2001birds]. In this paper, I will only be looking at gender homophily in co-author networks. According to research by @badar2016research, people prefer to work who they share some characteristics with, for example gender. When people share same characteristics, this is likely to make communication between people easier, and behaviour more predictable [@byrne1971attraction]. As one of the most visible characteristics is someone's sex, this could potentially be an important mechanism that explains the formation of collaborations for a scientific paper. If these assumptions are in play, it is highly likely that existing networks have already formed on the basis of these assumptions. This means that for example, men already have more ties with men, with positive experiences of collaboration, making it more likely that this man searches new ties with other male scientists. This leads to the following hypotheses: H1a: '*Men are more likely to collaborate with men*' and H1b: '*Women are more likely to collaborate with women*'.

Besides preferences being influenced by homophily, there could also be an effect of the mere underrepresentation of women in academia [@womeninacademia] that could potentially explain why there is a difference in collaboration networks between men and women. As there are more men in higher academic positions than women, only 28% of Dutch professors and 34% of associate professors are women [@womeninacademia] the pool of potential collaborators for a potential scientific paper is also skewed towards there being more men, this makes the basic likelihood of a collaborator being men larger. This exposure effect could also explain why there is a difference in the different composition of co-author networks for men than for women. This leads to the following hypothesis (H1c): '*Men are more likely to collaborate with men than women are likely to collaborate with women*'

Scientific collaboration networks have been shown to be highly clustered [@newman2001structure]. Furthermore, it has been shown that collaborations between researchers is more likely to occur whenever there is a third researcher that is connected to the collaborators, compared to random scientists [@barabasi2002evolution]. Assuming that homophily is one of the mechanisms that explains the origins and development of scientific collaboration networks, one expects that scientists prefer to work with people who are similar to themselves [@badar2016research]. Since there are more men than women in academia [@womeninacademia], it is statistically more likely for a random collaborator to be a man. 

With a higher number of career publications and co-authors, it is more likely that one is able to initiate new collaborations with scientists. Previous research (e.g. @newman2001structure) show that scientific collaboration networks are highly clustered, this can be partially ascribed to transitivity. Transitivity is the tendency among individuals to form a tie with another individual who already has a tie with someone known (e.g. becoming friends with friends of friends) [@block2015reciprocity]. Combining this idea transitivity with the preference of individuals to work with people who are alike themselves and the fact that there are more men in academia than women leads to the following hypothesis (H2): '*The transitivity effect is stronger for men than for women*'

A higher number of publications during someones' academic career has been found to influence the preference of others to work with this researcher [@matveeva2016citation]. Furthermore @sekara2018chaperone found that researchers in more senior positions (and who have published a higher number of papers) are more likely to collaborate with more junior researchers, so that these junior researchers can establish themselves in the field. Additionally, when researchers first start writing papers for publication, they prefer to work with researchers who have published more papers than themselves [@barabasi2002evolution; @li2007evolving; @perc2010growth]. This leads to the following hypothesis (H3): '*Researchers with more publications are more preferred for collaborations*'

# References
