---
title: "Methods"
output:
  html_document:
    toc: true
    number_sections: true
author: "by: Stijn van Helmondt"
bibliography: references.bib


---

# Methods

In order to be able to answer the research questions, there is a need for data. For this paper, I make use of a technique called 'webscraping'. Webscraping is a process by which a researcher collects data from the internet. In order to acquire these webscraped data, I have used the 'Scholar' package in R. This package allows for the gathering of information on publications, co-authors and citations of scientists. With this R-package, I scraped the information of the sociology staff of the Radboud University (N=...). 

Based on this data, the dependent variable (perc_sg) was created using the following code:

*insert code* 

Information on the gender of the scientist is found in the variable 'genderman', where men are coded with '1' and women with '0'.

The number of published papers --> information stored in 'num_pubs'. Staff with zero published papers have been removed from the sample, as they have no published papers, they can't have any co-authors and/or citations. 

One of the control variables in this paper is the seniority of the researcher. This is operationalised by looking at the number of years that someone has been involved in academia. Information on how long someone has been in academia has been stored in the variable 'career_age'


An overview of terminology and what is meant with what
Nodes The scientists of the sociology department

Edges Co-authorship between scientists (yes/no), directed

Dependent variable: Percentage of same-gender co-authors

Independent variable Gender, number of 

Control variables: Number of years in academia,  


## Preparation for week 3, what type of data do I need?

Type of information I need in my dataset:

- Gender of researcher  
- Age of researcher

- Number of articles published
- Amount of times the researcher has worked with a person --> could be an indicator of the strength of the relationship between researchers
- Speciality of topic of researcher -> lots of knowledge on specific, but niche, topics may be affecting the likelihood of fellow researchers wanting to work with you.
- Seniority -> how long has someone been in academia
- Average publications per year
- The number of working hours per week -> time available for academic writing


Whereas before looking at the SNASS chapter I was contemplating using the Radboud Social Science department as a sample, however, with the tutorial in mind, would it be better to take another university's Social Science staff as my sample?


Data can be undirected, as there is no information available on who initiated the collaboration for the paper(s). With wanting to know how often researchers have collaborated, I add weights to the ties between researchers. I believe that more collaborations can indicate a pleasant previous experiences when working together, so the combinations of characteristics are more likely to match, or influence preference for collaborations. 
As I will be looking at the collaborations between researchers, I will be looking at an egonetwerk structure type of data.

Afbakening: Sociologie faculteit RU
---